### ISSUE TITLE
Regards - Make specific rules to always ignore certain Applications-Programs when launched to only, floating state.. #681 quest

### ISSUE THREAD

**Issue by ComputerCulture** [lars-berger/glaze-wm#684]
### Describe the problem/motivation

Hi @lars-berger 
Lars, sorry to ask again, but i cant seem to get this to work correctly.  Note sure if i have put the code in the right place in the config file or how to do it so it works. .

As you told me in your reply
You can use a window rule with the set-floating command to always float a specific window, eg

  - commands: ['set-floating']
    match:
      - window_process: { equals: '<PROCESS NAME OF OUTLOOK>' }

At the moment from the screenshot attached is what i did, but this floats very application when i open up any app, no tiling.

![Rules](https://github.com/user-attachments/assets/0ffef738-bc28-4e84-b4a4-615183bd9f53)

### Describe the solution you'd like

Lars can you please explain where i have gone wrong, and how to apply this correctly and where in the config.yaml file...

Thank you Lars.

**Comment by Dimbel1** [comment]
Hey, you don't need <>. Just try this: equals: 'OUTLOOK' and it should work.
