### ISSUE TITLE
[Bug] The border Focus color does not always appear in the focus window when switching the window focus

### ISSUE THREAD

**Issue by DreamMaoMao** [lars-berger/glaze-wm#736]
### Describe the bug

I set the focus border color to purple, and then I had multiple Windows in a workspace, and when I switched the focus of the window, the border focus color didn't always show up。

### Reproduction

1.open three wt terminal
2.switch the window foucs one by one

### Version number

3.1.1

**Comment by lars-berger** [comment]
Fixed in v3.3.0 👍 Thanks for helping with tracking this down!
